{{- if gt (int .Values.controller.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lukscryptwalker-csi.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lukscryptwalker-csi.controller.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "lukscryptwalker-csi.controller.selectorLabels" . | nindent 6 }}
{{- end }}
