apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lukscryptwalker-local
provisioner: lukscryptwalker.csi.k8s.io
parameters:
  # Local path where volumes will be stored
  local-path: "/opt/local-path-provisioner"
  
  # LUKS encryption parameters
  # Reference to secret containing the passphrase
  csi.storage.k8s.io/node-stage-secret-name: "luks-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
  
  # Key name within the secret that contains the passphrase (default: "passphrase")
  passphraseKey: "passphrase"
  
  # Optional: specify filesystem type (default: ext4)
  # fsType: "ext4"

reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Secret
metadata:
  name: luks-secret
  namespace: kube-system
type: Opaque
data:
  # Base64 encoded passphrase (replace with your actual passphrase)
  # echo -n "your-secure-passphrase" | base64
  passphrase: eW91ci1zZWN1cmUtcGFzc3BocmFzZQ==

---
# Example PVC using the StorageClass
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lukscryptwalker-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lukscryptwalker-local
